
User.where(username: "Brooke").first_or_create(username: "Brooke", email: "brooke@brooke.com", password: "brooke")
User.where(username: "Lili").first_or_create(username: "Lili", email: "lili@lili.com", password: "lili")
User.where(username: "Caitlin").first_or_create(username: "Caitlin", email: "caitlin@caitlin.com", password: "caitlin")

Trip.where(name:"Paris").first_or_create(name:"Paris", description:"Paris, France's capital, is a major European city and a global center for art, fashion, gastronomy and culture. Its 19th-century cityscape is crisscrossed by wide boulevards and the River Seine. Beyond such landmarks as the Eiffel Tower and the 12th-century, Gothic Notre-Dame cathedral, the city is known for its cafe culture and designer boutiques along the Rue du Faubourg Saint-Honoré.", url:"https://travel.usnews.com/dims4/USNEWS/c5a8f6d/2147483647/resize/445x280%5E%3E/crop/445x280/quality/85/?url=https://travel.usnews.com/images/gettyimages-532590277_2ZNe4ra.jpg")
Trip.where(name:"Prague").first_or_create(name:"Prague", description:"Prague, capital city of the Czech Republic, is bisected by the Vltava River. Nicknamed “the City of a Hundred Spires,” it's known for its Old Town Square, the heart of its historic core, with colorful baroque buildings, Gothic churches and the medieval Astronomical Clock, which gives an animated hourly show.", url:"https://travel.usnews.com/dims4/USNEWS/d809244/2147483647/resize/445x280%5E%3E/crop/445x280/quality/85/?url=https://travel.usnews.com/images/main1_445x280_vOZ9p0Y.jpg")
Trip.where(name:"Berlin").first_or_create(name:"Berlin", description:"Berlin, Germany’s capital, dates to the 13th century. Reminders of the city's turbulent 20th-century history include its Holocaust memorial and the Berlin Wall's graffitied remains. Divided during the Cold War, its 18th-century Brandenburg Gate has become a symbol of reunification. The city's also known for its art scene and modern landmarks like the gold-colored, swoop-roofed Berliner Philharmonie, built in 1963.", url:"https://travel.usnews.com/dims4/USNEWS/2b5e50c/2147483647/resize/445x280%5E%3E/crop/445x280/quality/85/?url=https://travel.usnews.com/images/berlin_main_445x280_iVqQtBE.jpg")

TripHistory.where(user_id: 1, trip_id: 1).first_or_create(user_id: 1, trip_id: 1)
TripHistory.where(user_id: 2, trip_id: 2).first_or_create(user_id: 2, trip_id: 2)
TripHistory.where(user_id: 3, trip_id: 3).first_or_create(user_id: 3, trip_id: 3)